<?php
    function dbConnection(){
        $servername = "localhost";
        $username = "root";
        $password = "root";
        $dbname = "auth_system";

        $mysqli = new mysqli($servername, $username, $password, $dbname);

        if ($mysqli->connect_error) {
            die("Connection failed: " . $mysqli->connect_error);
        }
        return $mysqli;
    }
    function getUserFromDatabase($uname) {
        $mysqli = dbConnection();
     
        // Fetch user information based on the username
        $stmt = $mysqli->prepare("SELECT id, username, password FROM users WHERE username = ?");
        $stmt->bind_param("s", $uname);
        $stmt->execute();
        $stmt->bind_result($userId, $dbUsername, $dbPassword);
    
        $stmt->fetch();
    
        // Close the statement and connection
        $stmt->close();
        $mysqli->close();
    
        // Return user information if the user exists; otherwise, return null
        return $dbUsername ? ['id' => $userId, 'username' => $dbUsername, 'password' => $dbPassword] : null;
    }

     function saveUserToDatabase($username, $hashedPassword, $email, $address,$telephone) {
        $mysqli = dbConnection();

         $username = mysqli_real_escape_string($mysqli, $username);
         $email = mysqli_real_escape_string($mysqli, $email);
         $address = mysqli_real_escape_string($mysqli, $address);
         $telephone = mysqli_real_escape_string($mysqli, $telephone);

         if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
             return array('error' => 'Invalid email format');
         } else{
             $insertQuery = "INSERT INTO users (username, password, email, address,telephone) VALUES (?, ?, ?, ?,?)";
             $stmt = $mysqli->prepare($insertQuery);

             if ($stmt) {
                 $stmt->bind_param("sssss", $username, $hashedPassword, $email, $address,$telephone);
                 $stmt->execute();

                 // Get the user ID generated by the database (if applicable)
                 $userId = $stmt->insert_id;

                 // Close the statement
                 $stmt->close();
                 $mysqli->close();

                 return $userId;
             } else {
                 $mysqli->close();
                 return "Error in prepared statement: " . $mysqli->error;
             }
         }

    }
    
    function validateUserName($username) {
        $mysqli = dbConnection();

        $checkUsernameQuery = "SELECT * FROM users WHERE username = ?";   //reduce risk of sql injection
        $checkUsernameStmt = $mysqli->prepare($checkUsernameQuery);
        $checkUsernameStmt->bind_param("s", $username);
        $checkUsernameStmt->execute();
        $checkUsernameResult = $checkUsernameStmt->get_result();

        $isUsernameAvailable = ($checkUsernameResult->num_rows === 0);

        $checkUsernameStmt->close();
    
        return $isUsernameAvailable;
    }
 
    function getUserByGoogleId($google_id) {
        $mysqli = dbConnection();
    
        // Prepare the query to fetch user by Google ID
        $stmt = $mysqli->prepare("SELECT * FROM users WHERE google_id = ?");
        $stmt->bind_param("s", $google_id);
        $stmt->execute();
        $result = $stmt->get_result();
     
        // Fetch the user record
        $user = $result->fetch_assoc();
    
        // Close the statement and connection
        $stmt->close();
        $mysqli->close();
    
        return $user; // Return the user record
    }
    
    function incrementLoginAttempts($username) {
        $mysqli = dbConnection();

        $username = mysqli_real_escape_string($mysqli, $username);

        // Fetch the current number of login attempts
        $stmt = $mysqli->prepare("SELECT login_attempts FROM users WHERE username = ?");
        $stmt->bind_param("s", $username);
        $stmt->execute();
        $stmt->bind_result($loginAttempts);
        $stmt->fetch();
        $stmt->close();
    
        // Increment the number of login attempts
        $loginAttempts++;
    
        // Update the login_attempts column in the database
        $updateStmt = $mysqli->prepare("UPDATE users SET login_attempts = ? WHERE username = ?");
        $updateStmt->bind_param("is", $loginAttempts, $username);
        $updateStmt->execute();
        $updateStmt->close();
    
        // Close the connection
        $mysqli->close();
    }
    
    function isAccountLocked($username) {
        $mysqli = dbConnection();
        
        // Fetch the current number of login attempts
        $stmt = $mysqli->prepare("SELECT login_attempts FROM users WHERE username = ?");
        $stmt->bind_param("s", $username);
        $stmt->execute();
        $stmt->bind_result($loginAttempts);
        $stmt->fetch();
        $stmt->close();
    
        // Define your threshold for locking the account (e.g., 5 attempts)
        $maxAttempts = 3;
    
        // Check if the number of login attempts exceeds the threshold
        $isLocked = ($loginAttempts >= $maxAttempts);
    
        // Close the connection
        $mysqli->close();
    
        return $isLocked;
    }

function getUserById($userId) {
    $mysqli = dbConnection();
 
    // Fetch user information based on the user ID
    $stmt = $mysqli->prepare("SELECT id, username, email, address, telephone,password FROM users WHERE id = ?");
    $stmt->bind_param("i", $userId);  //to prevent sql injections ensures that the user input is treated as data, not code
    $stmt->execute();
    $stmt->bind_result($id, $username, $email, $address, $telephone,$passowrd);

    // Fetch the user record
    $stmt->fetch();

    // Close the statement and connection
    $stmt->close();
    $mysqli->close();

    // Return user information if the user exists; otherwise, return null
    return $username ? ['id' => $id, 'username' => $username, 'email' => $email, 'address' => $address, 'telephone' => $telephone,'password' => $passowrd] : null;
}
function updateUserPassword($userId, $hashedPassword) {
    $mysqli = dbConnection();

    // Prepare the query to update the user's password
    $stmt = $mysqli->prepare("UPDATE users SET password = ? WHERE id = ?");
    $stmt->bind_param("si", $hashedPassword, $userId);
    
    // Execute the statement and return success/failure
    $success = $stmt->execute();

    // Close the statement and connection
    $stmt->close();
    $mysqli->close();

    return $success;
}

function saveGoogleUserToDatabase($username,$email,$id){
    $mysqli = dbConnection();

    $username = mysqli_real_escape_string($mysqli, $username);
    $email = mysqli_real_escape_string($mysqli, $email);
    $id = mysqli_real_escape_string($mysqli, $id);

    if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
        return array('error' => 'Invalid email format');
    } else{
        $insertQuery = "INSERT INTO users (username,email, google_id) VALUES (?, ?, ?)";
        $stmt = $mysqli->prepare($insertQuery);

        if ($stmt) {
            $stmt->bind_param("sss", $username, $email,$id);
            $stmt->execute();

            // Get the user ID generated by the database (if applicable)
            $userId = $stmt->insert_id;

            // Close the statement
            $stmt->close();
            $mysqli->close();

            return $userId;
        } else {
            $mysqli->close();
            return "Error in prepared statement: " . $mysqli->error;
        }
    }
}

function resetLoginAttempts($username) {
    $mysqli = dbConnection();
    $resetQuery = "UPDATE users SET login_attempts = 0 WHERE username = ?";

    // Prepare the statement
    $stmt = $mysqli->prepare($resetQuery);

    // Bind parameters
    $stmt->bind_param("s", $username); // Use "i" for integer data type

    // Execute the statement
    $success = $stmt->execute();

    // Close the statement and database connection
    $stmt->close();
    $mysqli->close();

    // Return success/failure
    return $success;
}


function clearLoginAttempts($username) {
    $mysqli = dbConnection();

    // Define the time threshold (e.g., 1 hour)
    $clearTime = strtotime('-1 hour'); // Adjust as needed

    // Check if the last login attempt is older than the time threshold
    $stmt = $mysqli->prepare("SELECT last_login_attempt FROM users WHERE username = ?");
    $stmt->bind_param("s", $username);
    $stmt->execute();
    $stmt->bind_result($lastLoginAttempt);
    $stmt->fetch();
    $stmt->close();

    // If the last login attempt is older than the time threshold, reset login attempts to 0
    if ($lastLoginAttempt < $clearTime) {
        $updateStmt = $mysqli->prepare("UPDATE users SET login_attempts = 0 WHERE username = ?");
        $updateStmt->bind_param("s", $username);
        $updateStmt->execute();
        $updateStmt->close();
    }

    // Close the database connection
    $mysqli->close();
}

?>