<?php
    function getUserFromDatabase($username) {
        // Implement your database connection logic
        $servername = "localhost";
        $username = "root";
        $password = "root";
        $dbname = "auth_system";
            
        $mysqli = new mysqli($servername, $username, $password, $dbname);

        if ($mysqli->connect_error) {
            die("Connection failed: " . $mysqli->connect_error);
        }
        // ...
     
        // Fetch user information based on the username
        $stmt = $mysqli->prepare("SELECT id, username, password FROM users WHERE username = ?");
        $stmt->bind_param("s", $username);
        $stmt->execute();
        $stmt->bind_result($userId, $dbUsername, $dbPassword);
    
        // Fetch the result
        $stmt->fetch();
    
        // Close the statement and connection
        $stmt->close();
        $mysqli->close();
    
        // Return user information if the user exists; otherwise, return null
        return $dbUsername ? ['id' => $userId, 'username' => $dbUsername, 'password' => $dbPassword] : null;
    }

     // Store the user information in the database (you need to implement this part)
     function saveUserToDatabase($username, $hashedPassword, $email, $address) {
        // Establish a database connection (replace these variables with your actual database credentials)
        $servername = "localhost";
        $dbusername = "root";
        $dbpassword = "root";
        $dbname = "auth_system";
            
        $mysqli = new mysqli($servername, $dbusername, $dbpassword, $dbname);
        
        // Check for connection errors
        if ($mysqli->connect_error) {
            die("Connection failed: " . $mysqli->connect_error);
        }
    
        $insertQuery = "INSERT INTO users (username, password, email, address) VALUES (?, ?, ?, ?)";
    $stmt = $mysqli->prepare($insertQuery);

    if ($stmt) {
        $stmt->bind_param("ssss", $username, $hashedPassword, $email, $address);
        $stmt->execute();
        
        // Get the user ID generated by the database (if applicable)
        $userId = $stmt->insert_id;

        // Close the statement
        $stmt->close();
        $mysqli->close();
        
        return $userId;
    } else {
        $mysqli->close();
        return "Error in prepared statement: " . $mysqli->error;
    }
    }
    
    function validateUserName($username) {
        $servername = "localhost";
        $dbusername = "root";
        $dbpassword = "root";
        $dbname = "auth_system";
            
        $mysqli = new mysqli($servername, $dbusername, $dbpassword, $dbname);
        
        // Check for connection errors
        if ($mysqli->connect_error) {
            die("Connection failed: " . $mysqli->connect_error);
        }

        $checkUsernameQuery = "SELECT * FROM users WHERE username = ?";   //reduce risk of sql injection
        $checkUsernameStmt = $mysqli->prepare($checkUsernameQuery);
        $checkUsernameStmt->bind_param("s", $username);
        $checkUsernameStmt->execute();
        $checkUsernameResult = $checkUsernameStmt->get_result();

        $isUsernameAvailable = ($checkUsernameResult->num_rows === 0);

        $checkUsernameStmt->close();
    
        return $isUsernameAvailable;
    }
    ?>